"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^n)l%pdynkoys4z1rr#1_4449m=3bayos@6@guo!&xpq#(h77q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',  # must precede django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'corsheaders',
    # local apps
    'site_content',
    'inquiry',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Media (uploaded files) ──────────────────────────────────
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── CORS (dev): allow the Vue dev server / static front-end ──
# Tighten to specific origins in production.
CORS_ALLOW_ALL_ORIGINS = True

# ── Django REST Framework ───────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # rate limit for the feedback form (anti-spam); uses the default cache
    'DEFAULT_THROTTLE_RATES': {
        'inquiry': '10/hour',
    },
}

# ── Email (feedback notifications) ──────────────────────────
# Defaults to the console backend so submissions work out-of-the-box in dev
# (the email is printed to the runserver console). Set the EMAIL_* env vars
# below to a real SMTP host (e.g. Gmail / 腾讯企业邮 / SendGrid) in production.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@visionboard.studio')
# Where new-feedback alerts are sent.
FEEDBACK_NOTIFY_TO = os.environ.get('FEEDBACK_NOTIFY_TO', 'ylinylin1010@gmail.com')

# ── Simple UI (Chinese admin) ───────────────────────────────
SIMPLEUI_HOME_TITLE = '愿景板工作室 · 数据看板'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_STATIC_OFFLINE = True   # serve simpleui assets locally (no external CDN)
SIMPLEUI_LOGO = None
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# Explicit Chinese first/second level menu
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['网站内容', '咨询管理', '系统管理'],
    'dynamic': False,
    'menus': [
        {
            'name': '网站内容', 'icon': 'fas fa-folder-open',
            'models': [
                {'name': '站点信息', 'icon': 'fas fa-info-circle', 'url': '/admin/site_content/siteinfo/'},
                {'name': '业务分类', 'icon': 'fas fa-sitemap', 'url': '/admin/site_content/servicecategory/'},
                {'name': '业务栏目', 'icon': 'fas fa-th-list', 'url': '/admin/site_content/service/'},
                {'name': '案例展示', 'icon': 'fas fa-images', 'url': '/admin/site_content/showcase/'},
            ],
        },
        {
            'name': '咨询管理', 'icon': 'fas fa-comments',
            'models': [
                {'name': '咨询留言', 'icon': 'fas fa-envelope', 'url': '/admin/inquiry/inquiry/'},
            ],
        },
        {
            'name': '系统管理', 'icon': 'fas fa-cogs',
            'models': [
                {'name': '用户', 'icon': 'fas fa-user', 'url': '/admin/auth/user/'},
                {'name': '用户组', 'icon': 'fas fa-users', 'url': '/admin/auth/group/'},
            ],
        },
    ],
}
