# Generated by Django 5.1.15 on 2026-06-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '业务分类',
                'verbose_name_plural': '业务分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='案例标题')),
                ('description', models.TextField(blank=True, verbose_name='案例描述')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='封面图(URL 或相对路径)')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签(逗号分隔)')),
                ('featured', models.BooleanField(default=False, verbose_name='首页精选')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '案例展示',
                'verbose_name_plural': '案例展示',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='愿景板工作室', max_length=100, verbose_name='站点名称')),
                ('slogan', models.CharField(blank=True, max_length=200, verbose_name='标语')),
                ('intro', models.TextField(blank=True, verbose_name='简介')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='业务名称')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='一句话简介')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='图标(emoji/字符)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='site_content.servicecategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '业务栏目',
                'verbose_name_plural': '业务栏目',
                'ordering': ['order', 'id'],
            },
        ),
    ]
