# Generated by Django 5.1.15 on 2026-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式(电话/邮箱)')),
                ('subject', models.CharField(blank=True, max_length=120, verbose_name='咨询主题')),
                ('message', models.TextField(verbose_name='咨询内容')),
                ('source', models.CharField(default='官网表单', max_length=50, verbose_name='来源')),
                ('status', models.CharField(choices=[('new', '待处理'), ('contacted', '已联系'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '咨询留言',
                'verbose_name_plural': '咨询留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
